@hostname = http://localhost:8585

post {{hostname}}/placeStockOrder
# Sell Limit Order
Content-Type: application/json

{   "stock_id":1,
    "is_buy":false,
    "order_type":"LIMIT",
    "quantity":10,
    "price": 50
}

###

post {{hostname}}/placeStockOrder
# Buy Limit Order
Content-Type: application/json

{   "stock_id":1,
    "is_buy":true,
    "order_type":"LIMIT",
    "quantity":5,
    "price": 50
}

###

post {{hostname}}/placeStockOrder
# Sell market Order
Content-Type: application/json

{   "stock_id":2,
    "is_buy":false,
    "order_type":"MARKET",
    "quantity":3,
    "price": null
}

###
post {{hostname}}/placeStockOrder
# Buy Market Order
Content-Type: application/json

{   "stock_id":2,
    "is_buy":true,
    "order_type":"MARKET",
    "quantity":10,
    "price": null
}

###
post {{hostname}}/cancelStockTransaction
# Cancel Order
Content-Type: application/json

{   
    "stock_tx_id":"45c60517-20ce-4ab5-94de-58790801c4a1"
}