@hostname = http://localhost:8585

post {{hostname}}/placeStockOrder
# Sell Limit Order
Content-Type: application/json

{   "stock_id":2,
    "is_buy":false,
    "order_type":"LIMIT",
    "quantity":3,
    "price": 100
}

###

post {{hostname}}/placeStockOrder
# Buy Limit Order
Content-Type: application/json

{   "stock_id":2,
    "is_buy":true,
    "order_type":"LIMIT",
    "quantity":10,
    "price": 100
}

###

post {{hostname}}/placeStockOrder
# Sell market Order
Content-Type: application/json

{   "stock_id":2,
    "is_buy":false,
    "order_type":"MARKET",
    "quantity":369,
    "price": null
}

###

post {{hostname}}/placeStockOrder
# Buy Market Order
Content-Type: application/json

{   "stock_id":2,
    "is_buy":true,
    "order_type":"MARKET",
    "quantity":10,
    "price": null
}

###
post {{hostname}}/cancelStockTransaction
# Cancel Order
Content-Type: application/json

{   
    "stock_tx_id":"8a8287cd-6d8d-4adb-96d5-1b5e666c3a36"
}