POST http://localhost:5000/addMoneyToWallet
Content-Type: application/json
Authorization: Bearer <your_token_here>

{
    "amount": 100
}

###

GET http://localhost:5000/eatCookies
Authorization: Bearer <your_token_here>
