@hostname = http://localhost:8080

post {{hostname}}/createStock
Content-Type: application/json
 
{
    "stock_name": "Apple"
}

###

post {{hostname}}/addStockToUser
Content-Type: application/json

{
    "stock_id":"1",
    "quantity":300
}
