@hostname = http://localhost:8080

post {{hostname}}/createStock
Content-Type: application/json

{
    "stock_name": "AMD"
}

###

post {{hostname}}/addStockToUser
Content-Type: application/json

{
    "stock_id":"2",
    "quantity":1500
}
