@hostname = http://localhost:8888

post {{hostname}}/login
Content-Type: application/json

{
    "user_name": "test1",
    "password": "test001"
}

###

post {{hostname}}/register
Content-Type: application/json

{
    "user_name": "test1",
    "password": "test001",
    "name": "tester01"
}