@hostname = http://localhost:8888

post {{hostname}}/login
Content-Type: application/json

{
    "user_name": "test1",
    "password": "testpassword001"
}

###

post {{hostname}}/register
Content-Type: application/json

{
    "user_name": "test2",
    "password": "test002",
    "name": "tester02"
}

###

get {{hostname}}/eatCookies